name: Dockerize

on:
  #schedule:
  #- cron: "0 10 * * *" # everyday at 10am
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          # Use tags computed before and also latest if on master
          tags: inseefrlab/shelly
      - name: Build and push cloudshell
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          file: ./Dockerfile.cloudshell
          push: ${{ github.event_name != 'pull_request' }}
          # Use tags computed before and also latest if on master
          tags: inseefrlab/shelly:cloudshell
